<?php


namespace App\Repository\Repositories;

use App\Jobs\PostCreatedEmail;
use App\Models\Post;
use App\Repository\RepositoryInterfaces\PostRepositoryInterface;
use Illuminate\Support\Facades\Gate;

class PostRepository extends BaseRepository implements PostRepositoryInterface
{
    /**
     * PostRepository constructor.
     * @param Post $model
     */
    public function __construct(Post $model)
    {
        parent::__construct($model);
    }

    /**
     * @param array $attributes
     * @return mixed|void
     */
    public function create(array $attributes)
    {
        parent::create($attributes); // TODO: Change the autogenerated stub
        $email_job = new PostCreatedEmail();
        dispatch($email_job);
    }

    /**
     * @param null $user_id
     * @return mixed|void
     */
    public function selectWithUserOrWithout($user_id = null)
    {
        return parent::selectWithUserOrWithout($user_id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        if (Gate::denies('destroy',$post)){
            abort(403);
        };
        return parent::destroy($id);  // TODO: Change the autogenerated stub
    }

    /**
     * @param array $details
     * @param $id
     * @return mixed|void
     */
    public function update(array $details, $id)
    {
        parent::update($details, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id)
    {
        return parent::show($id) ; // TODO: Change the autogenerated stub
    }

}
