<?php


namespace App\Repository\Repositories;

use App\Models\Post;
use App\Repository\RepositoryInterfaces\PostRepositoryInterface;
use Illuminate\Database\Eloquent\Model;

class PostRepository extends BaseRepository implements PostRepositoryInterface
{
    /**
     * PostRepository constructor.
     * @param Post $model
     */
    public function __construct(Post $model)
    {
        parent::__construct($model);
    }

    /**
     * @param array $attributes
     * @return mixed|void
     */
    public function create(array $attributes)
    {
        parent::create($attributes); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $user_id
     * @return mixed|void
     */
    public function selectWithUserOrWithout($user_id = null)
    {
        return parent::selectWithUserOrWithout($user_id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        return parent::destroy($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $details
     * @param $id
     * @return mixed|void
     */
    public function update(array $details, $id)
    {
        parent::update($details, $id); // TODO: Change the autogenerated stub
    }

}
