<?php


namespace App\Repository\Repositories;


use App\Models\User;
use App\Repository\RepositoryInterfaces\UserRepositoryInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class UserRepository extends BaseRepository implements UserRepositoryInterface
{
    public function __construct(User $model)
    {
        parent::__construct($model);
    }

    /**
     * @param array $attributes
     * @return User
     */
      public function create(array $attributes)
      {
          parent::create($attributes); // TODO: Change the autogenerated stub
      }


    /**
     * @param array $details
     * @param $id
     * @return mixed|void
     */
      public function update(array $details, $id)
      {
          parent::update($details, $id); // TODO: Change the autogenerated stub
      }
}
