<?php


namespace App\Repository\Repositories;


use App\Jobs\MatchSendEmail;
use App\Models\User;
use App\Repository\RepositoryInterfaces\UserRepositoryInterface;
use Carbon\Carbon;

class UserRepository extends BaseRepository implements UserRepositoryInterface
{
    public function __construct(User $model)
    {
        parent::__construct($model);
    }

    /**
     * @param array $attributes
     * @return User
     */
      public function create(array $attributes)
      {
          parent::create($attributes); // TODO: Change the autogenerated stub
          $user = User::where('email',$attributes['email'])->first();
          $email_job = new MatchSendEmail($user);
          dispatch($email_job);
          return $user;
      }


    /**
     * @param array $details
     * @param $id
     * @return mixed|void
     */
      public function update(array $details, $id)
      {
          parent::update($details, $id); // TODO: Change the autogenerated stub
      }

    /**
     * @param $id
     * @return mixed|void
     */
      public function verify_email($id)
      {
          User::find($id)->update(['email_verified_at'=> Carbon::now()]);
      }

    /**
     * @param $id
     * @return bool
     */
      public function checkIfEmailIsVerified($id)
      {
          if (User::find($id)->email_verified_at){
              return true;
          }
          return false;
      }
}
